CREATE UNIQUE INDEX IF NOT EXISTS IDX_ENGINE_GAME_VARIANTS 
ON EngineGameVariants (AssetId, VersionId);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_GAME_VARIANTS 
ON GameVariants (AssetId, VersionId);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_INVENTORY_ITEMS
ON InventoryItems (Path);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_MAPS
ON Maps (AssetId, VersionId);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_MATCH_STATS
ON MatchStats (MatchId);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_OPERATION_REWARD_TRACKS
ON OperationRewardTracks (Path);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_PLAYLISTS
ON Playlists (AssetId, VersionId);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_PLAYLIST_MAP_MODE_PAIRS
ON PlaylistMapModePairs (AssetId, VersionId);