name: Publish In-Repo NuGet Package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        source-url: ${{ env.NUGET_URL }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
    - name: Verify commit exists in origin/master
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/master
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build
      working-directory: ./src/OpenSpartan.Workshop
      run: dotnet build --configuration Release
    - name: Test
      working-directory: ./src/OpenSpartan.Workshop
      run: dotnet test --configuration Release --no-build
    - name: Install WiX
      run: dotnet tool install --global wix
    - name: Build WiX on Windows
      run: wix build .\src\OpenSpartan.Workshop.Installer\OpenSpartan.Workshop.Installer.wix
